services:
  postgres_primary:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@55w0rd!
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
  postgres_replica:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@55w0rd!
      POSTGRES_DB: postgres
    ports:
      - '5433:5432'
    depends_on:
      - postgres_primary
    command: >
      postgres -c max_wal_senders=3
               -c wal_level=hot_standby
               -c hot_standby=on
               -c primary_conninfo='host=postgres_primary user=user password=P@55w0rd! port=5432'
               -c restore_command='cp /var/lib/postgresql/data/archive/%f %p'
               -c archive_mode=on
               -c archive_command='test ! -f /var/lib/postgresql/data/archive/%f && cp %p /var/lib/postgresql/data/archive/%f'
  redis_cache:
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  redis_data:

