
x-postgres-common: &postgres-common
  image: postgres:15-alpine
  restart: unless-stopped
  healthcheck:
    test: 'pg_isready -U user --dbname=postgres'
    interval: 10s
    timeout: 5s
    retries: 5
services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: unless-stopped
  postgres_primary:
    <<: *postgres-common
    container_name: postgres_primary
  postgres_replica:
    <<: *postgres-common
    container_name: postgres_replica
  redis_cache:
    image: redis:alpine
    container_name: "redis_cache"


  gateway_service:
    image: ${DOCKER_REGISTRY-}service
    container_name: gateway_service
    build:
      context: .
      dockerfile: Yarp.Gateway/Dockerfile


  product_service:
    image: ${DOCKER_REGISTRY-}service
    container_name: product_service
    build:
      context: .
      dockerfile: product/Product.Service/Dockerfile

  notification_service:
    image: ${DOCKER_REGISTRY-}service
    container_name: notification_service
    build:
      context: .
      dockerfile: notification/Notification.Service/Dockerfile

